"""user cards comments relation

Revision ID: 03f81543fdf4
Revises: 4ab8219ddf26
Create Date: 2021-03-26 00:59:00.396639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03f81543fdf4'
down_revision = '4ab8219ddf26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'card', 'user', ['user_id'], ['id'])
    op.add_column('comment', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'user_id')
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_column('card', 'user_id')
    # ### end Alembic commands ###
