"""comment self referential relation

Revision ID: a668fde3d991
Revises: 03f81543fdf4
Create Date: 2021-03-26 01:20:14.986339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a668fde3d991'
down_revision = '03f81543fdf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('parent_comment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'comment', ['parent_comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'parent_comment_id')
    # ### end Alembic commands ###
