"""card title not unique

Revision ID: fce420e8c909
Revises: a668fde3d991
Create Date: 2021-03-26 03:06:41.287753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fce420e8c909'
down_revision = 'a668fde3d991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('card_title_key', 'card', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('card_title_key', 'card', ['title'])
    # ### end Alembic commands ###
